### ISSUE TITLE
Make it usable by other bots

### ISSUE THREAD

**Issue by jayvdb** [fernand0/err-social#1]
We (@coala) are interested in twitter functionality (https://github.com/coala/corobo/issues/172), and I see you have some here, but the code mentions your twitter username (and facebook, and maybe others).

It would be great if the twitter command was able to be configured to work with a different username.

**Comment by fernand0** [comment]
It is on my to do list to clean it (and to pass it to configuration), any patch would be welcome. It shouldn't be difficult to do.

**Comment by fernand0** [comment]
It was easy. It was a controlled issue that I hardcoded for the shake of simplicity in testing. The code needs more cleaning, anyway.
